name: lyghts
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  chopper: ^2.4.0
  provider: ^3.0.0+1
  get_it: ^3.1.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  chopper_generator: ^2.3.4
  build_runner:
  mockito: 4.0.0


flutter:
  uses-material-design: true
